const translations = {
  // Navigation sidebar & groups
  "Dashboard": "Bảng điều khiển",
  "Custom": "Tùy chỉnh",
  "All Requests": "Tất cả yêu cầu",
  "Pending Approvals": "Đang chờ duyệt",
  "Borrow Equipment": "Mượn thiết bị",
  "History Log": "Nhật ký lịch sử",
  "Schedules": "Lịch khả dụng",
  "FAQ": "Hỏi đáp (FAQ)",
  
  // Dashboard & widgets
  "Pending Approval Requests": "Yêu cầu đang chờ duyệt",
  "Overdue Returns": "Trả đồ quá hạn",
  "Near Due Borrowed Equipment": "Thiết bị sắp đến hạn trả",
  "My Requests & Borrows": "Yêu cầu & lượt mượn của tôi",
  "Requester": "Người yêu cầu",
  "Equipment": "Thiết bị",
  "University / Purpose": "Trường / Mục đích",
  "Classroom": "Phòng học",
  "Actions": "Thao tác",
  "Approve": "Duyệt",
  "Deny": "Từ chối",
  "No pending approval requests.": "Không có yêu cầu nào đang chờ duyệt.",
  "Borrower": "Người mượn",
  "Due Date": "Hạn trả",
  "Action": "Thao tác",
  "Email Reminder": "Gửi mail nhắc nhở",
  "Extend 7d": "Gia hạn 7 ngày",
  "Send Reminder": "Gửi nhắc nhở",
  "Purpose": "Mục đích",
  "Status": "Trạng thái",
  "Edit": "Chỉnh sửa",
  "Return": "Trả đồ",
  "You have no active requests or borrows.": "Bạn không có yêu cầu hoặc thiết bị mượn hoạt động nào.",
  
  // Request lists and filters
  "All Requests & Borrows": "Tất cả Yêu cầu & Lượt mượn",
  "Prioritized request lifecycle view with advanced search and filters.": "Xem chu kỳ yêu cầu theo độ ưu tiên với tìm kiếm nâng cao và bộ lọc.",
  "Search by equipment, requester, location...": "Tìm kiếm theo thiết bị, người yêu cầu, vị trí...",
  "All Statuses": "Tất cả trạng thái",
  "Borrowed": "Đang mượn",
  "Returned": "Đã trả",
  "Cancelled": "Đã hủy",
  "All Purposes": "Tất cả mục đích",
  "Classroom": "Phòng học",
  "Vovinam Room": "Phòng võ Vovinam",
  "Lab": "Phòng Lab",
  "Research": "Nghiên cứu",
  "Event": "Sự kiện",
  "Priority & Status": "Độ ưu tiên & Trạng thái",
  "Purpose & Details": "Mục đích & Chi tiết",
  "Classroom/Location": "Phòng học/Vị trí",
  "Quantity: ": "Số lượng: ",
  "Unit: ": "Học phần: ",
  "Returned: ": "Đã trả lúc: ",
  "Edit request details": "Chỉnh sửa chi tiết yêu cầu",
  "Extend borrowing by 7 days": "Gia hạn mượn thêm 7 ngày",
  "View or update chain of custody": "Xem hoặc cập nhật nhật ký bàn giao",
  "Send email reminder to borrower": "Gửi mail nhắc nhở người mượn",
  "Remind": "Nhắc nhở",
  "No requests matching your filters were found.": "Không tìm thấy yêu cầu nào phù hợp với bộ lọc.",
  
  // History log
  "Borrowing History Log": "Nhật ký Lịch sử Mượn thiết bị",
  "Search, filter, and view past and active borrow requests.": "Tìm kiếm, lọc và xem các yêu cầu mượn thiết bị trong quá khứ và hiện tại.",
  "Search items, users, classroom...": "Tìm kiếm thiết bị, người dùng, phòng học...",
  "Requested": "Đang chờ duyệt",
  "Approved": "Đã duyệt",
  "Near Due Date": "Sắp đến hạn trả",
  "Overdue": "Quá hạn",
  "Date Created": "Ngày tạo",
  "Start Date": "Ngày bắt đầu",
  "Returned Date": "Ngày trả đồ",
  "Ascending": "Tăng dần",
  "Descending": "Giảm dần",
  "No.": "STT",
  "User": "Người dùng",
  "Borrowed At": "Mượn lúc",
  "Due At": "Hạn trả",
  "Returned At": "Trả lúc",
  "No borrow history records match filters.": "Không có nhật ký lịch sử mượn nào khớp với bộ lọc.",
  "Showing ": "Hiển thị ",
  " of ": " trên ",
  " records": " bản ghi",
  "Previous": "Trang trước",
  "Next": "Trang sau",
  
  // Schedules View
  "Equipment Availability Schedule": "Lịch khả dụng của thiết bị",
  "Live 24h × 7-day availability per item from real bookings. Click a green slot to reserve at that exact time.": "Lịch khả dụng trực quan 24h × 7 ngày từ các lượt mượn thực tế. Nhấp vào ô màu xanh để đặt lịch tại thời điểm đó.",
  "Select Equipment:": "Chọn thiết bị:",
  "Working Hours (08:00 - 22:00)": "Giờ làm việc (08:00 - 22:00)",
  "Current Status:": "Trạng thái hiện tại:",
  "Location: ": "Vị trí: ",
  "Currently borrowed by ": "Hiện đang được mượn bởi ",
  " until ": " cho đến ",
  "Available (Click to book)": "Khả dụng (Nhấp để đặt)",
  "Reserved / Borrowed": "Đã đặt / Đang mượn",
  "Out of service": "Đang bảo trì/hỏng",
  "Past": "Đã qua",
  "Reserve ": "Đặt mượn thiết bị ",
  "Classroom Instruction": "Giảng dạy trên lớp",
  "Research Work": "Nghiên cứu khoa học",
  "Swinburne Event": "Sự kiện Swinburne",
  "Reason of Use:": "Lý do sử dụng:",
  "University:": "Trường đại học:",
  "Cancel": "Hủy bỏ",
  "Confirm Reservation": "Xác nhận đặt lịch",
  "Reserving...": "Đang đặt lịch...",
  "Open": "Trống",
  "Booked": "Đã đặt",
  "Out": "Hỏng",
  
  // Profile View
  "Role": "Vai trò",
  "User ID": "Mã người dùng",
  "Joined Date": "Ngày tham gia",
  "Supervisor / Lecturer": "Giảng viên hướng dẫn",
  "Active Borrows": "Đang mượn hoạt động",
  "Total History": "Tổng lịch sử",
  "Recent Borrow Activity": "Hoạt động mượn gần đây",
  "Asset: ": "Mã tài sản: ",
  "No borrow activity found.": "Không tìm thấy hoạt động mượn thiết bị nào.",
  
  // FAQ View
  "Frequently Asked Questions": "Các câu hỏi thường gặp",
  "Find answers to common questions about the Swinburne Equipment Portal.": "Tìm câu trả lời cho các câu hỏi thường gặp về Cổng thiết bị Swinburne.",
  "Need more help?": "Cần thêm hỗ trợ?",
  "Read our portal documentation or guidelines for detailed information on student and lecturer policies.": "Đọc tài liệu hướng dẫn hoặc nội quy cổng thông tin để biết chi tiết về chính sách cho sinh viên và giảng viên.",
  "View Guidelines": "Xem hướng dẫn",
  "Contact Swinburne Vietnam Support Desk for emergency equipment requests or physical support.": "Liên hệ Bàn hỗ trợ Swinburne Việt Nam cho các yêu cầu thiết bị khẩn cấp hoặc hỗ trợ kỹ thuật trực tiếp.",
  
  // Edit Borrow Modal
  "Modify Borrow Request": "Chỉnh sửa yêu cầu mượn đồ",
  "Details": "Chi tiết",
  "Recurrence": "Lặp lại",
  "Single Session": "Một buổi duy nhất",
  "Repeat Daily": "Lặp lại hàng ngày",
  "Repeat Weekly (Within Semester)": "Lặp lại hàng tuần (Trong học kỳ)",
  "Repeat Bi-weekly": "Lặp lại mỗi 2 tuần",
  "Repeat Monthly": "Lặp lại hàng tháng",
  "Save Changes": "Lưu thay đổi",
  
  // Topbar and profile menu
  "Hi, ": "Xin chào, ",
  "My Profile": "Hồ sơ của tôi",
  "Sign Out": "Đăng xuất",
  
  // Overdue warnings & Statuses
  "OVERDUE": "QUÁ HẠN",
  "NEAR_DUE": "SẮP HẾT HẠN",
  "REQUESTED": "ĐANG CHỜ DUYỆT",
  "BORROWED": "ĐANG MƯỢN",
  "RETURNED": "ĐÃ TRẢ",
  "CANCELLED": "ĐÃ HỦY",
  
  // Purpose names
  "CLASSROOM": "GIẢNG DẠY",
  "VOVINAM": "PHÒNG VÕ VOVINAM",
  "LAB": "PHÒNG LAB",
  "RESEARCH": "NGHIÊN CỨU",
  "EVENT": "SỰ KIỆN",
  
  // Notifications
  "Notifications": "Thông báo",
  
  // Chain of custody modal
  "Chain of custody — ": "Chuỗi bàn giao thiết bị — ",
  "No custody entries yet.": "Chưa có nhật ký bàn giao nào.",
  "Add custody entry": "Thêm nhật ký bàn giao",
  "Who holds it now / condition...": "Ai đang giữ / tình trạng thiết bị...",
  "Handover": "Bàn giao",
  "Checked out": "Đã lấy đồ",
  "Transfer": "Chuyển giao",
  "Inspected": "Đã kiểm tra",
  "From": "Từ",
  "To": "Đến",
  "Notes": "Ghi chú",
  
  // Status panel & others
  "Lecturer": "Giảng viên",
  "Student": "Sinh viên",
  "Event Coordinator": "Điều phối viên sự kiện",
  "Support Desk": "Bàn hỗ trợ",
  "Admin": "Quản trị viên",
  // FAQ Questions
  "How do I request to borrow equipment?": "Làm cách nào để yêu cầu mượn thiết bị?",
  "Go to the 'Borrow Equipment' tab in the side menu. Select the equipment you need, enter the quantity, and choose the purpose (Classroom, Lab, Research, or Event). Enter the location and due date, then submit. If you are a Student, your request will require Support Desk approval. Lecturers and Event Staff can borrow immediately.": "Vào tab 'Mượn thiết bị' ở menu phụ bên trái. Chọn thiết bị cần mượn, nhập số lượng, và chọn mục đích (Lên lớp, Lab, Nghiên cứu, hoặc Sự kiện). Điền vị trí phòng học và ngày trả, sau đó gửi yêu cầu. Nếu bạn là Sinh viên, yêu cầu sẽ cần Bàn hỗ trợ phê duyệt. Giảng viên và Nhân viên sự kiện được duyệt mượn ngay lập tức.",
  "What is the new Location format?": "Định dạng Vị trí mới là gì?",
  "Locations now follow the 'Campus-Building-Room' composite key format. For example: 'HN-ATC-625' (Hanoi campus, ATC building, Room 625), 'HN-LIB-DESK' (Hanoi campus, Library Desk), or 'HN-BA-701' (Hanoi campus, BA building, Room 701).": "Các vị trí hiện tuân theo định dạng mã gộp 'Cơ sở-Tòa nhà-Phòng'. Ví dụ: 'HN-ATC-625' (cơ sở Hà Nội, tòa ATC, phòng 625), 'HN-LIB-DESK' (cơ sở Hà Nội, bàn thư viện), hoặc 'HN-BA-701' (cơ sở Hà Nội, tòa BA, phòng 701).",
  "What is the new Asset Code format?": "Định dạng Mã tài sản mới là gì?",
  "Asset codes follow the 'brand-assetTag-id' composite key format. For example, a Logitech camera kit would have an asset code like 'Logitech-LRC-001'. This allows unique identification of specific brands and inventory tags.": "Mã tài sản tuân theo định dạng gộp 'thương hiệu-nhãnTàiSản-mãSố'. Ví dụ: một bộ camera Logitech sẽ có mã tài sản như 'Logitech-LRC-001'. Điều này giúp nhận dạng duy nhất từng thương hiệu và nhãn kiểm kê.",
  "How do I return borrowed equipment?": "Làm cách nào để trả lại thiết bị?",
  "To return equipment, go to the 'Confirm Return' section, find your active borrowing request, and submit a return. A Support Desk staff member will inspect the equipment, confirm the returned quantity, mark the condition (OK or Damaged), and complete the return process.": "Để trả thiết bị, hãy đến phần 'Xác nhận trả đồ', tìm yêu cầu mượn hoạt động của bạn và tiến hành trả đồ. Nhân viên Bàn hỗ trợ sẽ kiểm tra thiết bị, xác nhận số lượng trả lại, đánh dấu tình trạng (OK hoặc Hỏng) và hoàn tất quá trình trả đồ.",
  "What is the Chain of Custody feature?": "Tính năng Chuỗi bàn giao (Chain of Custody) là gì?",
  "For Event bookings, the system maintains a detailed chain of custody log. Each time the equipment is handed over, checked out, transferred, or inspected, the holder must record the action and condition notes in the custody log to ensure complete accountability.": "Đối với lượt mượn Sự kiện, hệ thống duy trì nhật ký bàn giao chi tiết. Mỗi khi thiết bị được bàn giao, lấy ra, chuyển giao hoặc kiểm tra, người nắm giữ phải ghi lại thao tác và ghi chú tình trạng để đảm bảo trách nhiệm giải trình đầy đủ.",
  "Borrowing": "Mượn đồ",
  "Returning": "Trả đồ",
  "General": "Chung",
  // Reasons & Purposes
  "Teaching": "Giảng dạy",
  "Student Presentation": "Thuyết trình của sinh viên",
  "Exam/Quiz": "Thi/Kiểm tra",
  "Seminar/Workshop": "Hội thảo/Chuyên đề",
  "Lab Session": "Buổi thực hành Lab",
  "Club Activity": "Hoạt động Câu lạc bộ",
  "Other": "Khác",
  "Classroom Instruction": "Giảng dạy trên lớp",
  "Research Work": "Nghiên cứu khoa học",
  "Swinburne Event": "Sự kiện Swinburne",
  "Swinburne": "Swinburne",
  "Asia": "Asia",
  "FPT": "FPT",
  "Today": "Hôm nay",
  "Quantity": "Số lượng",
  "Handover Notes": "Ghi chú bàn giao"
};

export function makeTranslator(email) {
  const isVovinam = email === "vovinamteacher@fpt.edu.vn";
  return (text) => {
    if (!isVovinam) return text;
    if (typeof text !== "string") return text;
    const clean = text.trim();
    return translations[clean] || translations[clean.toLowerCase()] || text;
  };
}
